### ISSUE TITLE
Please implement wallbox support

### ISSUE THREAD

**Issue by AgentP38** [torbennehmer/hacs-e3dc#54] opened 2023-09-13 06:30 UTC
### Checklist

- [X] I have filled out the template to the best of my ability.
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).
- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/torbennehmer/hacs-e3dc/issues?q=is%3Aissue+label%3A%22Feature+Request%22+).

### Is your feature request related to a problem? Please describe.

Actual for me the regulation of the charging current preset is neccessary to create automations for solar charging.

### Describe the solution you'd like

please add a input number for e3dc_wallbox_preset_charging_current

and in addition the othe neccessary wallbox functionality

### Describe alternatives you've considered

I tried to connect via modbus but preset_charging_current has no address

**Comment by frank2604** [comment] 2023-10-07 07:17
+1, please! I have two E3/DC easy conntect wallboxes. I switch over from ioBroker to HA. In ioBroker there is also an integration via rscp. If I can help with any datapoints for wallboxes, please let me know.

**Comment by wall121** [comment] 2023-10-28 17:00
+ another one, using Multi Connect II Wallbox ;-)

**Comment by torbennehmer** [comment] 2024-01-15 18:19
Duplicate of #47

**Closed by torbennehmer** 2024-01-15 18:19 UTC
Labels: enhancement
